version: "3.3"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    # volumes:
    #   - /volume1/docker/lablogs/config:/etc/loki/
    network_mode: bridge
    volumes:
      - /volume1/docker/lablogs/loki:/loki
      - /volume1/docker/lablogs/config/loki-lab.yaml:/etc/loki/loki.yaml

  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng
    restart: unless-stopped
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /volume1/docker/lablogs/config/syslog-ng.conf:/config/syslog-ng.conf
      - /volume1/docker/lablogs/syslog-ng:/config
      # - /volume1/docker/lablogs/loki:/var/log
    network_mode: bridge
    ports:
      - 5514:5514/udp
#      - 6601:6601/tcp
#      - 6514:6514/tcp

  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   network_mode: bridge
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /volume1/docker/lablogs/loki/:/var/log/
      - /volume1/docker/lablogs/config/promtail.yaml:/etc/promtail/promtail.yaml
    ports:
      - "9080:9080"
      - "1514:1514"
    command: -config.file=/etc/promtail/promtail.yaml
    network_mode: bridge

  grafana:
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_FEATURE_TOGGLES_ENABLE: "alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode"
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      # - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    # entrypoint:
    #   - sh
    #   - -euc
    #   - |
    #     mkdir -p /etc/grafana/provisioning/datasources
    #     cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
    #     apiVersion: 1
    #     datasources:
    #     - name: Loki
    #       type: loki
    #       access: proxy 
    #       orgId: 1
    #       url: http://synergy:3100
    #       basicAuth: false
    #       isDefault: true
    #       version: 1
    #       editable: false
    #     EOF
    #     /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    network_mode: bridge
    volumes:
      - /volume1/docker/lablogs/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - /volume1/docker/lablogs/grafana:/var/lib/grafana
